### PR TITLE
192-Inspect csproj to find the appconfig location

### PR DESCRIPTION
**Pull request by itanneo**
Fix bug issue #192
The App.config file may not be in the project items but it can be defined in the csproj file in the PropertyGroup->AppConfig element

## Types of changes

- [ X] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Performance improvement
- [ ] Refactoring (so no functional change)
- [ ] Other (docs, build config, etc)

## Checklist:

- [ ] I've added tests for my code. (most of the time mandatory)
- [ ] I have added an entry to the changelog. (mandatory)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by SabotageAndi** [comment]
@epresi & @gasparnagy could you have a look at this?
Is this also something we need to adjust in the VS2022 extension?

**Comment by gasparnagy** [comment]
@SabotageAndi it has to be checked. The config file loading is done differently, but it might not support shared app config files.

**Comment by itanneo** [comment]
Hello guys
Any news about that PR ?

**Comment by epresi** [comment]
Thanks for your contribution to SpecFlow. Sorry that it took so long until we had a look at it.
Please submit your contributions to our SpecFlow Community Heroes program at https://specflow.org/community/submit-a-contribution/

**Review by epresi — APPROVED** [review]

**Pull request merged**
