### PR TITLE
Initial version for supporting step argument suggestions for enum types

### PR DESCRIPTION
**Pull request by Renreok**
I implemented an initial version for step argument suggestions when editing feature files in Visual Studio. It is at least a first step to solve [Issue #1850](https://github.com/SpecFlowOSS/SpecFlow/issues/1850). See also my comment there for more information about this change.

Since this is my first contribution to SpecFlow, I'd like to share some thoughts and questions I had during implementation:

1. Would it make sense / is it possible to implement step argument suggestions in dedicated classes? From my perspective there is a large overlap with the existing step suggestions, so I did most of the implementation directly in the existing classes. I'm also not sure if Visual Studio would support e.g. the registration of a second completion source for Gherkin files.
2. The new method VsBindingRegistryBuilder.GetStepArgumentTypesFromProjectItem introduces some computational overhead, because it processes the project item another time. This could be done more efficiently in the existing GetBindingsFromProjectItem method. This would need some deeper refactoring of existing code, which I tried to avoid in this first step.
3. Classes BindingFileInfo, VsStepSuggestionProvider, FileStepDefinitions and StepSuggestionProvider were extended with lists / dictionaries of step argument types. Here I'm unsure if this should be implemented at least partially in dedicated classes, or if some of the classes should be renamed. E.g. it makes sense to hold information about step definitions and step argument types defined in a single file in one class (FileStepDefinitions), but it could make sense to change the class name (e.g. to FileDefinitions).
4. As a consequence, class StepMap now also includes information about step argument types, including the serialization into the cache file. I think it makes sense to have all information in a single cache file (otherwise there would be a lot of overhead for writing/reading two cache files, and potentially some inconsistency between the files). However, as mentioned before, a different naming might improve code readability. On the other hand, step definitions and step arguments are still quite closely related, so the existing naming might also be ok.
5. I'm a bit concerned about the VSTHRD010 warnings reporting access to VS objects from the wrong thread. Although there were already a lot of such warnings before (and to my understanding the objects are indeed often accessed from a wrong thread), my additional code might raise the probability of stability problems. At least from time to time I get NullReference exceptions at DTE object access during VS shutdown, when I have the debugger attached and save a code file shortly before closing VS.
6. Are there any automated tests that need to be adapted? At least I did not find anything about automated integration tests for Visual Studio.
7. Which configurations should be tested? So far I only tested with VS2019 and English language setting.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Performance improvement
- [ ] Refactoring (so no functional change)
- [ ] Other (docs, build config, etc)

## Checklist:

- [ ] I've added tests for my code. (most of the time mandatory)
- [ ] I have added an entry to the changelog. (mandatory)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by epresi** [comment]
Hey @Renreok,

Thanks for the PR. I took a look in the past days. First, let me try to answer your questions:
1. It would be the best, if the current suggestion providers could be re-used/extended to support the step argument suggestions. I didn't check in detail, but when we scan/analyze the binding class(es) we have every information in our hand. You already added a code which creates a list of `StepArgumentType` in the [VsBindingRegistryBuilder](https://github.com/Renreok/SpecFlow.VisualStudio/blob/0554ca5584abc1a4e550a73e3e838f0f50d756c5/TechTalk.SpecFlow.VsIntegration.Implementation/Bindings/Discovery/VsBindingRegistryBuilder.cs#L41). So in theory we have a list of `StepArgumentType` and a binding: 
`
 [Given("the first number is (.*)")]
 public void GivenTheFirstNumberIs(int number) {  _scenarioContext.Pending();  }
`
where we know the parameter type, which we could use for the suggestions/completions. 
2. Instead of a bigger refactoring, we could add the step argument suggestions to a place which is connected to the Bindings. 
3. Again, if we have the bindings and the step arguments in the same place/class, I think this problem will be solved.
4. It is a good idea to have it in the cache in this way.
5. I think we cannot do anything with the warnings, unless we put a lot of work into it.
6. As you saw already, there are only a few tests in the solution. There are parts which we cannot automate, so we usually do manual testing.
7. I personally try my changes with VS2019 and VS2017.

Regarding the code:
- I saw some duplicate code, especially in the `AugmentCompletionSession` method's [if-else statement](https://github.com/Renreok/SpecFlow.VisualStudio/blob/StepArgumentSuggestions/TechTalk.SpecFlow.VsIntegration.Implementation/AutoComplete/GherkinStepCompletionSource.cs#L57-L110)
   - `IsKeywordPrefix` should be used to decide if the text in the line is a keyword prefix or not
      - Because of this, the `else if` statement is only true if the line contains a keyword only
      - Because of this, if you ask for a completion (ctrl+space) the implementation in the PR does nothing - unless the cursor stands at a point where an enum parameter is expected
- I would keep this part as simple as possible (check if keyword completion is needed or step text completion) 
- Maybe we can get rid of the limitations you mentioned in [GetCurrentStepArgumentType](https://github.com/Renreok/SpecFlow.VisualStudio/blob/0554ca5584abc1a4e550a73e3e838f0f50d756c5/TechTalk.SpecFlow.VsIntegration.Implementation/AutoComplete/GherkinStepCompletionSource.cs#L324) if we have the connected binding.

After some manual testing:
- The old implementation was able to make suggestions even if the cursor was in the end of a step text
   - This is currently not working, I think because of the previous problem

**Comment by Renreok** [comment]
Thanks a lot for reviewing the PR and your comments.

I don't understand your comment of putting the step argument suggestions to a place which is connected to the bindings. To some extent the step argument suggestions and bindings are already known to VsStepSuggestionProvider, which already stores suggestion information for bindings and step arguments. Can you explain a bit more, how you meant that?

You are absolutely right about the redundancy in GherkinStepCompletionSource.AugmentCompletionSession. There is not only redundancy in the if/else statement, but also in the called functions [GetCurrentBindingType](https://github.com/Renreok/SpecFlow.VisualStudio/blob/0554ca5584abc1a4e550a73e3e838f0f50d756c5/TechTalk.SpecFlow.VsIntegration.Implementation/AutoComplete/GherkinStepCompletionSource.cs#L240) and [GetCurrentStepArgumentType](https://github.com/Renreok/SpecFlow.VisualStudio/blob/0554ca5584abc1a4e550a73e3e838f0f50d756c5/TechTalk.SpecFlow.VsIntegration.Implementation/AutoComplete/GherkinStepCompletionSource.cs#L324) (e.g. both retrieve the step definition at the current line). This should probably be done in a single function, which would help to remove redundancy and probably also fixes the bug you found during your testing. I'll have a look at this and try to provide a fix.

The todos in [GetCurrentStepArgumentType](https://github.com/Renreok/SpecFlow.VisualStudio/blob/0554ca5584abc1a4e550a73e3e838f0f50d756c5/TechTalk.SpecFlow.VsIntegration.Implementation/AutoComplete/GherkinStepCompletionSource.cs#L324) are probably harder to solve.
The first todo would probably need an extension of TechTalk.SpecFlow.Bindings.StepInstance to include also information about trailing whitespace as well as a change to TechTalk.SpecFlow.Infrastructure.IStepDefinitionMatchService.GetBestMatch() to consider this whitespace.
The second todo would also need an alternative implementation of GetBestMatch() to find a match also when the step arguments don't match the RegEx from the binding definition. But this second todo might practically have only little relevance, because I guess most bindings capture arguments anyway by (.*).

**Comment by epresi** [comment]
Hey @Renreok,
Sorry for the late reply, I had other duties.
So, maybe I expressed myself badly. Let me try to rephrase what I wrote last time.
For a `BindingFileInfo` we know all of the `IStepDefinitionBinding`(TechTalk.SpecFlow.Bindings.StepDefinitionBinding), stored in 2 places: 
- `BindingFileInfo.StepBindings`
- `bindingSuggestions` dict

My idea was that if we already know everything about a binding method, couldn't we use that information to suggest the enum for the user?
A bit in detail:
For example I have a binding method:
```c#
[When(@"I execute (.*) operation")]
public void WhenIExecuteOperation(Operation op)
{
     ScenarioContext.Current.Pending();
}
```
Where `Operation` is a simple enum:
```c#
public enum Operation
{
   Add,
   Divide
}
```

What we know about this Step definition (`TechTalk.SpecFlow.Bindings.StepDefinitionBinding`) looks like this:
```json
"StepDefinitionType": "When",
"Regex": {},
"IsScoped": false,
"Method": {
	"Type": {
		"Name": "CalculatorStepDefinitions",
		"FullName": "SpecFlowProject47.Steps.CalculatorStepDefinitions"
	},
	"Name": "WhenIExecuteOperation",
	"Parameters": [
		{
			"Type": {
				"Name": "Operation",
				"FullName": "SpecFlowProject47.Steps.Operation"
			},
			"ParameterName": "op"
		}
	]
}
```
Maybe this can be used instead of the `GetCurrentStepArgumentType` method. As far as I saw the `Method.Type` from the above json sample is the type of the same `IBindingType` type returned by your method.
Also, maybe in this way you can get rid of most of the todos/limitations of `GetCurrentStepArgumentType`.
So if you remove the method above, and combine the `else-if` and the `else`, you will have a chance to extend the `GetNativeSuggestionItems` of the base `StepSuggestionProvider` with the suggestion of the enum values/names, it could produce something like this:
combined
I didn't dig myself really into this, but maybe the above one is not the best place to extend the Completion, because there is some kind of filtering logic [here](https://github.com/SpecFlowOSS/SpecFlow.VisualStudio/blob/master/TechTalk.SpecFlow.VsIntegration.Implementation/AutoComplete/CompletionCommandFilter.cs#L129-L131). (Which may drop out the enums)
Note: Auto completion starts [here](https://github.com/SpecFlowOSS/SpecFlow.VisualStudio/blob/master/TechTalk.SpecFlow.VsIntegration.Implementation/AutoComplete/CompletionCommandFilter.cs#L123).

What do you think about this approach?

**Comment by Renreok** [comment]
Hi Balázs,

it seems that we are thinking about different ways, how the step argument suggestions shall be provided to the user. I was assuming, that the user would first pick a step definition and then fill our the step arguments. In my current version, this is still a bit cumbersome, because the step argument must be selected first, and by hitting space, the list of argument suggestions would open up (alternatively, the user could select the argument, remove it with del, and invoke auto-completion with Ctrl-space). In a future version, this could be optimized by selecting the argument automatically when a step suggestion is inserted and jumping to the next argument when the first argument is inserted, etc.

Can you describe how you would envision the user interaction? Do you expect the user to first type "I execute " before suggesting the options for `Operation`?

Another question: How do you find all the possible values for `Operation`. They must be stored somewhere, and the binding is probably not the right place (because the same `Operation` type could be used by multiple bindings, and it could be defined in a different source file or assembly, i.e. change independently from the step definition).

Mario

**Comment by epresi** [comment]
Hi Mario,

Looks like we imagined the step argument suggestions in a different way, but it is fine. To be honest I have no problem with the solution you wrote. However currently the extension is not capable of suggesting a step definition, and then jumping to the first argument, suggest, jump to the next, etc.
What I wrote could be a first initiative of step argument suggestions. Simply suggest everything, which could fit there.

Currently the extension only suggests (automatically):
- keywords
- step definitions after a keyword
- if the user invokes the auto-completion (ctrl+space)

I think it is not a problem if the user have to invoke the auto-completion functionality.

> Can you describe how you would envision the user interaction? Do you expect the user to first type "I execute " before suggesting the options for `Operation`?

This is exactly how I imagined. The extension is suggesting the user text which occurs somewhere else in a feature file:
image
So if the user already used all the values of an enum, it will be in the list anyway. If not, well yes, I imagined that she/he will go there and invokes the auto-completion.

> Another question: How do you find all the possible values for `Operation`. They must be stored somewhere, and the binding is probably not the right place (because the same `Operation` type could be used by multiple bindings, and it could be defined in a different source file or assembly, i.e. change independently from the step definition).

This I didn't think about yet. Without checking the code, I think the way you collect/store the enum values is fine, but if you have any doubt I'll take a look.

**Comment by Renreok** [comment]
Hi Balázs,

I'm still thinking about your last comment. What you suggest would indeed solve some of the todos in [GetCurrentStepArgumentType](https://github.com/Renreok/SpecFlow.VisualStudio/blob/0554ca5584abc1a4e550a73e3e838f0f50d756c5/TechTalk.SpecFlow.VsIntegration.Implementation/AutoComplete/GherkinStepCompletionSource.cs#L324), e.g. the problem when the step argument appears at the end of the step text. But there are also some drawbacks:
- If we implement this solution now, and switch over to my proposal later, then this will be a change in the user experience. This could cause confustion for some users.
- Adding all enum values to the step suggestions can lead to a lot of step suggestions when enums with a lot of values are involved (e.g. a set of colors). This would multiply when a step has multiple enum parameters, e.g. `"[Given] a box with border color (.*) and background color (.*)"` ...
- The previous point might displease users, which are not even interested in step argument suggestions.
- The same step suggestion could appear multiple times, because the enum value could be spelled differently (e.g. upper/lower case, with/without spaces).

I tend to try to implement my suggestion completely (i.e. selecting the step argument automatically) and see how it feels.

Regarding your last question: I already wrote my concerns in my fist post. But after the discussion, I think it's good enough for now.
Just one new question: VsStepSuggestionProvider defines a [`Dictionary<BindingFileInfo, List<IStepDefinitionBinding>> bindingSuggestions`](https://github.com/SpecFlowOSS/SpecFlow.VisualStudio/blob/0554ca5584abc1a4e550a73e3e838f0f50d756c5/TechTalk.SpecFlow.VsIntegration.Implementation/LanguageService/VsStepSuggestionProvider.cs#L23) although BindingFileInfo already defines a [`IEnumerable<IStepDefinitionBinding> StepBindings`](https://github.com/SpecFlowOSS/SpecFlow.VisualStudio/blob/0554ca5584abc1a4e550a73e3e838f0f50d756c5/TechTalk.SpecFlow.VsIntegration.Implementation/LanguageService/BindingFileInfo.cs#L14). What is the reason for copying the step definition bindings? I did the same for the step arguments by following the same pattern, but I don't know why it's done like that.

**Comment by Renreok** [comment]
I fixed my implementation now, so the step suggestions are shown when auto-comletion is invoked at a position which does not belong to a step argument. If invoked at a step argument, the step argument suggesions are shown.
I also rebased my branch to master.

Now that I'm writing these lines, I'm wondering whether it would be better to only show the step argument suggestions in case there are any, and to fall back to step suggestions in all other cases (e.g. when triggered at a non-enum argument)...

**Comment by SabotageAndi** [comment]
@Renreok Thanks for your work, but we decided that we won't merge this pull request.
The reason is, that we changed our approach for Visual Studio 2022 support. Because of this changed approach, we won't have this feature in VS2022 from the start as it will be pretty sure based on a different implementation.
As we don't want to have fewer features in the new extension, we will not add this. And with the work for the VS 2022 extension, we don't have enough time to make this now rather complicated pull request finished from our side.

**Comment by Renreok** [comment]
It's a pity to read that, because it worked pretty well for me. I'm still looking forward to the new implementation of the VS 2022 extension (will you resolve the threading issues? - this concerned me a bit), and hope that it will support step argument suggestions at some point in time. I consider this a really important feature, because I would like to enable some team members with rather low technical experience to write feature files. For them it's rather inconvenient to jump into the step implementation and check the step argument options.
Let me know when the new implementation is at a state where this feature could be added. Perhaps I could again spend some time.

**Pull request closed without merging**
