### PR TITLE
Remove \r character after format if the file did not have it before

### PR DESCRIPTION
**Pull request by darakeon**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Performance improvement
- [ ] Refactoring (so no functional change)
- [ ] Other (docs, build config, etc)

## Checklist:

- [ ] I've added tests for my code. (most of the time mandatory)
- [ ] I have added an entry to the changelog. (mandatory)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by SabotageAndi** [comment]
Sorry for the late feedback. It is quite busy here in the last few weeks. We will have a look at the PR in the next few days.

**Review by epresi — APPROVED** [review]

**Comment by darakeon** [comment]
I sent a pull request at moment (the datetime javascript library) some years ago and it was never answered. Thanks for this, people. My first contribution to a open source project that is not mine neither of a company I'm working for.

**Comment by SabotageAndi** [comment]
Thanks for your contribution to SpecFlow. Sorry that it took so long until we had a look at it.
Please submit your contributions to our SpecFlow Community Heroes program at https://specflow.org/community/submit-a-contribution/

**Comment by darakeon** [comment]
21 days is not that much! And you made me really happy!

**Pull request merged**
