### PR TITLE
Improvement of the default specflow example

### PR DESCRIPTION
**Pull request by tawfiknouri**
Improvement of the default specflow example, UI elements have been removed
A good BDD scenario should focus on “What” not “How”

## Types of changes

- [x] Other (docs, build config, etc)

## Checklist:

- [ ] I've added tests for my code. (most of the time mandatory)
- [ ] I have added an entry to the changelog. (mandatory)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by 304NotModified** [comment]
Disagree on this one change. Business users do enter number on calculators.

**Comment by tawfiknouri** [comment]
@304NotModified 

You have the answer in the same artilce !
> Most software does something people could do manually (just not as efficiently).
> Try hard to come up with examples that don’t make any assumptions about technology. Imagine it’s 1922, when there were no computers.

**When you use "I press add" and "I have entered" you think about technology and how the system work and not how the system does
We need to separate the "What" from the "How", the scenario is about addition and not about UI 
UI may be GUI, Web API, console ..**.

@SabotageAndi  do you agree ?

Thanks

**Comment by 304NotModified** [comment]
"Given a first number 50"

You almost can't describe it more abstract...

**Comment by tawfiknouri** [comment]
Here an example :
https://github.com/tawfiknouri/BDD-TDD_ParkingCostCalculator_SpecFlow/blob/master/specs/ParkCostCalc.Core.Specs/Features/ShortTerm.feature

We use specflow scenarios as executables specification to drive the implementation and not as testing tools....

**Comment by SabotageAndi** [comment]
Dave Farley is talking in this video https://youtu.be/zYj70EsD7uI?t=605 exactly about this example.

I like the change for the `When` and `Then` steps. For the `Given` I am a little bit unsure. It's a little bit too vague for me.

**Comment by tawfiknouri** [comment]
@SabotageAndi @304NotModified 

This version my be more better  ?

if you agree i can update my PR

```
Feature: $itemname$
	In order to avoid silly mistakes
	As a math idiot
	I want to be told the sum of two numbers

@v3
Scenario: Add two numbers
	Given the first number is 50
	And the second number is 70
	When the two numbers are added
	Then the result should be 120
```

**Comment by SabotageAndi** [comment]
Yes, I like the V3!

**Comment by ozslab** [comment]
@tawfiknouri : Thank you for your proposed changes regarding the feature file.
Could you please also update the step definition template files (`SpecFlowStepDefinition1.cs`, `SpecFlowStepDefinition1.fs` and `SpecFlowStepDefinition1.vb` in the `SpecFlowStepDefinition` folder) to match the updated feature file and include them into this PR?

**Comment by tawfiknouri** [comment]
@ozslab @SabotageAndi 

https://github.com/SpecFlowOSS/SpecFlow.VisualStudio/pull/87
Have a nice day.

**Comment by ozslab** [comment]
@tawfiknouri : That is great, thank you. Have a nice day.

**Pull request closed without merging**
